---
version: 1
build_arg_defaults:
  EE_BASE_IMAGE: 'quay.io/ansible/ansible-runner:stable-2.12-latest'
dependencies:
  galaxy: _build/requirements.yml
  python: _build/requirements.txt
  system: _build/bindep.txt
additional_build_steps:
  append:
    - RUN alternatives --set python /usr/bin/python3
    - COPY --from=docker.io/guywithnose/sqlplus:latest /usr/sbin/sqlplus /usr/sbin/sqlplus
    - COPY --from=docker.io/guywithnose/sqlplus:latest /usr/lib/libsqlplus.so /usr/lib/libsqlplus.so
    - COPY --from=docker.io/guywithnose/sqlplus:latest /usr/lib/libsqlplusic.so /usr/lib/libsqlplusic.so
    - COPY --from=docker.io/guywithnose/sqlplus:latest /usr/lib/libclntsh.so.12.1 /usr/lib/libclntsh.so.12.1
    - COPY --from=docker.io/guywithnose/sqlplus:latest /usr/lib/libclntshcore.so.12.1 /usr/lib/libclntshcore.so.12.1
    - COPY --from=docker.io/guywithnose/sqlplus:latest /usr/lib/libnnz12.so /usr/lib/libnnz12.so
    - COPY --from=docker.io/guywithnose/sqlplus:latest /usr/lib/libnsl.so.1 /usr/lib/libnsl.so.1
    - COPY --from=docker.io/guywithnose/sqlplus:latest /usr/lib/libnsl-2.19.so /usr/lib/libnsl-2.19.so
    - COPY --from=docker.io/guywithnose/sqlplus:latest /usr/lib/libons.so /usr/lib/libons.so
    - COPY --from=docker.io/guywithnose/sqlplus:latest /usr/lib/libaio.so.1 /usr/lib/libaio.so.1
    - COPY --from=docker.io/guywithnose/sqlplus:latest /usr/lib/libaio.so.1.0.1 /usr/lib/libaio.so.1.0.1
    - COPY --from=docker.io/guywithnose/sqlplus:latest /usr/lib/libociei.so /usr/lib/libociei.so
    - COPY --from=docker.io/juouyang/oracle-db:19.3.0-se2 /opt/oracle/product/19c/dbhome_1/suptools/oratop/oratop /usr/sbin/oratop
    - COPY --from=docker.io/juouyang/oracle-db:19.3.0-se2 /opt/oracle/product/19c/dbhome_1/lib/libclntsh.so.19.1 /usr/lib/libclntsh.so.19.1
    - COPY --from=docker.io/juouyang/oracle-db:19.3.0-se2 /opt/oracle/product/19c/dbhome_1/lib/libclntshcore.so.19.1 /usr/lib/libclntshcore.so.19.1
    - COPY --from=docker.io/juouyang/oracle-db:19.3.0-se2 /opt/oracle/product/19c/dbhome_1/lib/libnnz19.so /usr/lib/libnnz19.so
    - ENV LD_LIBRARY_PATH="/usr/lib/:$LD_LIBRARY_PATH"
    - ENV ORACLE_HOME="/usr"
    - USER 1000
